dependencies:
  - jupyter
  - ipykernel
  - planet
  - requests
  - numpy
  - geojson
  - pandas
  - geopandas
  - rasterio
  - fiona
  - geojsonio
  - shapely
  - mercantile
  - scikit-image
  - scikit-learn
  - matplotlib
  - humanize
  - ipyleaflet
  - ipyleaflet
  - ipywidgets
  - ipyvolume
  - altair
  - jq
  - vega_datasets
  - bqplot
  - nbdime
  - palettable
  - earthengine-api
  - folium
